properties:
  workflow_form:
    default: []
    description: This field describes the workflow configuration that will be populated
      as per what is entered on the form interface in the canvas.
    items:
      anyOf:
      - $ref: ../workflows/QueryForm.yaml
      - $ref: ../workflows/DatasetNode.yaml
      - $ref: ../workflows/ModelTrainNode.yaml
      - $ref: ../workflows/ModelArtifactNode.yaml
    title: Workflow Form
    type: array
title: WorkflowCreationConfig
type: object
