get:
  description: Lists all the created sources
  operationId: list_sources_api_v2_connectors_sources_get
  parameters:
    - name: x-correlation-id
      in: header
      description: correlation id to track requests
      schema:
        type: string
  responses:
    '200':
      content:
        application/json:
          schema:
            allOf:
            - $ref: '../../schemas/ResponseTemplateSuccessNoData.yaml'
            - type: object
              properties:
                data:
                  $ref: '../../schemas/connectors_hub/SourceOut.yaml'
      description: Successful Response
  summary: List Sources
  tags:
    - connectors
post:
  description: creates given source
  operationId: create_source_api_v2_connectors_sources_post
  parameters:
    - name: x-correlation-id
      in: header
      description: correlation id to track requests
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: '../../schemas/connectors_hub/CreateSource.yaml'
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            allOf:
            - $ref: '../../schemas/ResponseTemplateSuccessNoData.yaml'
            - type: object
              properties:
                data:
                  $ref: '../../schemas/connectors_hub/SourceID.yaml'
      description: Successful Response
    '422':
      content:
        application/json:
          schema:
            $ref: '../../schemas/HTTPValidationError.yaml'
      description: Validation Error
  summary: Create Source
  tags:
    - connectors